// /secure/language_d.c
// 語系守護進程 (Language Daemon)
// 集中管理系統性關鍵字與 UI 標籤，具備高共用性

#include "/include/ansi.h"

mapping translations;

void create() {
    translations = ([
        "en": ([
            "welcome": "Welcome back, $name.",
            "what": "What?",
            "cmd_not_found": "Command not found.",
            "prompt_id": "Please enter your account name:",
            "prompt_id_empty": "ID cannot be empty, please re-enter:",
            "prompt_pass": "Password:",
            "prompt_pass_wrong": "Wrong password, please re-enter:",
            "prompt_new_pass": "Welcome new player $id! Set your password:",
            "prompt_new_pass_empty": "Password cannot be empty, set again:",
            "login_success": "Login successful! Welcome, $name.",
            "void": "You are floating in the void.",
            "not_found": "You don't see any '$arg' here.",
            "exits": "Exits",
            "inventory": "Items",
            "livings": "Here are",
            "none": "None",
            "inv_empty": "Your inventory is empty.",
            "inv_header": "You are carrying the following items:",
            "get_what": "Get what?",
            "no_container": "There is no container called '$id' here.",
            "is_closed": "is closed.",
            "here": "here",
            "no_item_here": "You don't see any '$id' in $loc.",
            "get_living_err": "You cannot pick up living things.",
            "too_heavy_err": "is too heavy or fixed in place.",
            "loot_protected_err": "The loot of this corpse is protected, you cannot take it yet.",
            "inv_full_err": "Your inventory is full.",
            "corpse_run_success": "✨ You retrieved your remains, feeling your soul enriched and restoring some lost exp and potential.",
            "get_money": "You opened the money bag and obtained $m copper coins.",
            "ground": "the ground",
            "get_success": "You picked up $item from $from.",
            "say_get": "picked up",
            "get_fail": "You failed to take that item.",
            "drop_what": "Drop what?",
            "no_item_inv": "You don't have any '$id' in your inventory.",
            "no_drop_err": "seems stuck to your hands, you cannot drop it!",
            "drop_success": "You dropped $item.",
            "say_drop": "dropped",
            "drop_fail": "You cannot drop that item right now.",
            "go_where": "Go where? (e.g. go north)",
            "no_exit_err": "There is no exit in that direction.",
            "dest_missing_err": "The destination does not exist.",
            "say_leave": "$name left towards $dir.",
            "say_arrive": "$name arrived from $dir.",
            "move_fail_err": "You cannot go $dir.",
            "wear_what": "Wear what?",
            "not_armour_err": "is not armour.",
            "lv_req_err": "Your level is too low to equip $item (requires level $lv).",
            "wear_fail": "Failed to wear",
            "wear_success": "You put on $item. (Defence +$def)",
            "wield_what": "Wield what?",
            "not_weapon_err": "is not a weapon.",
            "wield_fail": "Failed to wield",
            "wield_success": "You wielded $item. (Attack +$atk)",
            "remove_what": "Remove what?",
            "remove_success": "You removed $item.",
            "no_equip_inv": "You are not equipped with anything called '$id'.",
            "appraise_what": "Appraise what?",
            "appraising": "You carefully examine $item...",
            "unidentified_err": "This item is not identified yet, you cannot see its detailed stats.",
            "item_info": "Item Info",
            "type": "Type",
            "weight": "Weight",
            "value": "Value",
            "coin_gold": "Gold Coins",
            "durability": "Durability",
            "lv_req": "Level Req",
            "atk_bonus": "Attack Bonus",
            "attribute": "Attribute",
            "def_bonus": "Defence Bonus",
            "slot": "Slot"
        ]),
        "zh-TW": ([
            "welcome": "歡迎回來，$name。",
            "what": "什麼？",
            "cmd_not_found": "找不到該指令。",
            "prompt_id": "請輸入您的帳號名稱：",
            "prompt_id_empty": "帳號不能為空，請重新輸入：",
            "prompt_pass": "請輸入密碼：",
            "prompt_pass_wrong": "密碼錯誤，請重新輸入密碼：",
            "prompt_new_pass": "歡迎新玩家 $id！為您的帳號設定密碼：",
            "prompt_new_pass_empty": "密碼不能為空，請重新設定密碼：",
            "login_success": "登入成功！歡迎來到這個世界，$name。",
            "void": "你飄浮在虛空中。",
            "not_found": "你看不到叫「$arg」的東西。",
            "exits": "出口",
            "inventory": "物品",
            "livings": "這裡有",
            "none": "無",
            "inv_empty": "你身上沒有任何東西。",
            "inv_header": "你身上帶著以下物品：",
            "get_what": "撿起什麼？",
            "no_container": "這裡沒有叫「$id」的容器。",
            "is_closed": "是關著的。",
            "here": "這裡",
            "no_item_here": "$loc 沒有叫「$id」的東西。",
            "get_living_err": "你不能撿起活物。",
            "too_heavy_err": "太重了，或者是被固定住了，你拿不起來。",
            "loot_protected_err": "這具屍體的戰利品暫時受保護，你目前無法拿取。",
            "inv_full_err": "你的背包裝不下了。",
            "corpse_run_success": "✨ 你取回了自己的遺物，靈魂感到一陣充實，恢復了部分損失的經驗與潛能。",
            "get_money": "你打開了錢袋，獲得了 $m 銅幣。",
            "ground": "地上",
            "get_success": "你從 $from 撿起了 $item。",
            "say_get": "撿起了",
            "get_fail": "你無法拿走這個物品。",
            "drop_what": "丟下什麼？",
            "no_item_inv": "你身上沒有叫「$id」的東西。",
            "no_drop_err": "似乎黏在你的手上了，丟不掉！",
            "drop_success": "你放下了 $item。",
            "say_drop": "放下了",
            "drop_fail": "你現在沒辦法丟下這個東西。",
            "go_where": "要往哪裡去？例如：go north",
            "no_exit_err": "那個方向沒有出路。",
            "dest_missing_err": "目的地不存在。",
            "say_leave": "$name 往 $dir 方向離開了。",
            "say_arrive": "$name 從 $dir 方向來到了這裡。",
            "move_fail_err": "你往 $dir 走不過去。",
            "wear_what": "穿上什麼？",
            "not_armour_err": "不是防具。",
            "lv_req_err": "你的等級不足，無法裝備 $item (需要等級 $lv)。",
            "wear_fail": "無法裝備",
            "wear_success": "你穿上了 $item。（防禦力 +$def）",
            "wield_what": "裝備什麼武器？",
            "not_weapon_err": "不是武器。",
            "wield_fail": "無法裝備",
            "wield_success": "你裝備了 $item。（攻擊力 +$atk）",
            "remove_what": "脫下什麼？",
            "remove_success": "你脫下了 $item。",
            "no_equip_inv": "你沒有裝備叫「$id」的東西。",
            "appraise_what": "鑑定什麼？",
            "appraising": "你仔細觀察 $item...",
            "unidentified_err": "這件物品尚未被鑑定，你看不出它的具體深淺。",
            "item_info": "物品資訊",
            "type": "種類",
            "weight": "重量",
            "value": "價值",
            "coin_gold": "金幣",
            "durability": "耐久",
            "lv_req": "需求等級",
            "atk_bonus": "攻擊力",
            "attribute": "屬性",
            "def_bonus": "防禦力",
            "slot": "部位"
        ]),
        "zh-CN": ([
            "welcome": "欢迎回來，$name。",
            "what": "什么？",
            "cmd_not_found": "找不到该指令。",
            "prompt_id": "请输入您的账号名称：",
            "prompt_id_empty": "账号不能为空，请重新输入：",
            "prompt_pass": "请输入密码：",
            "prompt_pass_wrong": "密码错误，请重新输入密码：",
            "prompt_new_pass": "欢迎新玩家 $id！为您的账号设定密码：",
            "prompt_new_pass_empty": "密码不能为空，请重新设定密码：",
            "login_success": "登录成功！欢迎來到这个世界，$name。",
            "void": "你飘浮在虚空中。",
            "not_found": "你看不到叫「$arg」的东西。",
            "exits": "出口",
            "inventory": "物品",
            "livings": "这里有",
            "none": "无",
            "inv_empty": "你身上没有任何东西。",
            "inv_header": "你身上带着以下物品：",
            "get_what": "捡起什么？",
            "no_container": "这里没有叫「$id」的容器。",
            "is_closed": "是关着的。",
            "here": "这里",
            "no_item_here": "$loc 没有叫「$id」的东西。",
            "get_living_err": "你不能捡起活物。",
            "too_heavy_err": "太重了，或者是被固定住了，你拿不起来。",
            "loot_protected_err": "這具屍體的戰利品暫時受保護，你目前無法拿取。",
            "inv_full_err": "你的背包裝不下了。",
            "corpse_run_success": "✨ 你取回了自己的遗物，灵魂感到一阵充实，恢复了部分损失的经验与潜能。",
            "get_money": "你打开了钱袋，获得了 $m 铜币。",
            "ground": "地上",
            "get_success": "你从 $from 捡起了 $item。",
            "say_get": "捡起了",
            "get_fail": "你无法拿走这个物品。",
            "drop_what": "丢下什么？",
            "no_item_inv": "你身上没有叫「$id」的东西。",
            "no_drop_err": "似乎黏在你的手上了，丢不掉！",
            "drop_success": "你放下了 $item。",
            "say_drop": "放下了",
            "drop_fail": "你现在没办法丟下这个东西。",
            "go_where": "要往哪里去？例如：go north",
            "no_exit_err": "那个方向没有出路。",
            "dest_missing_err": "目的地不存在。",
            "say_leave": "$name 往 $dir 方向离开了。",
            "say_arrive": "$name 从 $dir 方向来到了这里。",
            "move_fail_err": "你往 $dir 走不过去。",
            "wear_what": "穿上什么？",
            "not_armour_err": "不是防具。",
            "lv_req_err": "你的等级不足，无法装备 $item (需要等级 $lv)。",
            "wear_fail": "无法装备",
            "wear_success": "你穿上了 $item。（防御力 +$def）",
            "wield_what": "装备什么武器？",
            "not_weapon_err": "不是武器。",
            "wield_fail": "无法装备",
            "wield_success": "你装备了 $item。（攻击力 +$atk）",
            "remove_what": "脱下什么？",
            "remove_success": "你脱下了 $item。",
            "no_equip_inv": "你没有装备叫「$id」的东西。",
            "appraise_what": "鉴定什么？",
            "appraising": "你仔细观察 $item...",
            "unidentified_err": "這件物品尚未被鑑定，你看不出它的具體深淺。",
            "item_info": "物品信息",
            "type": "种类",
            "weight": "重量",
            "value": "价值",
            "coin_gold": "金币",
            "durability": "耐久",
            "lv_req": "需求等级",
            "atk_bonus": "攻击力",
            "attribute": "属性",
            "def_bonus": "防御力",
            "slot": "部位"
        ])
    ]);
}

string translate(string key, string lang) {
    if (!lang || !translations[lang]) {
        if (strsrch(lang, "zh-") == 0) lang = "zh-TW";
        else lang = "en";
    }

    if (translations[lang] && translations[lang][key]) {
        return translations[lang][key];
    }
    
    return key;
}

mapping query_all_translations() { return translations; }
