string *ALLOW_CHOICE =({
    "armor",
    "weapon",
//armor
    "head",
    "neck",
    "cloth",
    "armbands",
    "pants",
    "waist",
    "wrists",
    "shield",
    "finger",
    "hands",
    "boots",
    "cape",
    "leggings",
//weapon
    "axe",
    "blade",
    "claw",
    "chain",
    "dagger",
    "hammer",
    "sword",
    "staff",
    "stick",
    "bow",
    "arrow",
    "unarmed",
    "throwing",
    "whip",
    "stabber",
    "lance",
});
string *ARMOR_CHOICE= ({
    "armor",
    "head",
    "neck",
    "cloth",
    "armbands",
    "pants",
    "waist",
    "wrists",
    "shield",
    "finger",
    "hands",
    "boots",
    "cape",
    "leggings",
});
string *WEAPON_CHOICE= ({
    "weapon",
    "axe",
    "blade",
    "claw",
    "chain",
    "dagger",
    "hammer",
    "sword",
    "staff",
    "stick",
    "bow",
    "arrow",
    "unarmed",
    "throwing",
    "whip",
    "stabber",
    "lance",
});
mapping KIND_NAME =([
    "armor"      : "防具",
    "weapon"     : "武器",
    "other"      : "非武器防具物品",
    "head"       : "頭部防具",
    "neck"       : "頸部防具",
    "cloth"      : "上身防具",
    "armbands"   : "臂部防具",
    "pants"      : "下身防具",
    "waist"      : "腰部防具",
    "wrists"     : "腕部防具",
    "shield"     : "盾牌",
    "finger"     : "戒指",
    "hands"      : "手部防具",
    "boots"      : "腳部防具",
    "cape"       : "背部防具",
    "leggings"   : "膝部防具",
    "axe"        : "斧類兵器",
    "blade"      : "刀類兵器",
    "claw"       : "爪類兵器",
    "dagger"     : "匕首類兵器",
    "hammer"     : "槌類兵器",
    "sword"      : "劍類兵器",
    "staff"      : "杖類兵器",
    "stick "     : "棍類兵器",
    "bow"        : "弓",
    "arrow"      : "箭",
    "unarmed"    : "空手武器",
    "throwing"   : "丟擲暗器",
    "whip"       : "鞭類兵器",
    "stabber"    : "刺擊兵器",
    "lance"      : "槍類兵器",
]);
