// /secure/language_d.c
// 語系守護進程 (Language Daemon)
// 集中管理系統性關鍵字與 UI 標籤，具備高共用性

#include "/include/ansi.h"

inherit "/std/object";

mapping translations;

void create() {
    ::create();
    translations = ([
        "en": ([
            "welcome": "Welcome back, $name.",
            "what": "What?",
            "cmd_not_found": "Command not found.",
            "prompt_id": "Please enter your account name:",
            "prompt_id_empty": "ID cannot be empty, please re-enter:",
            "prompt_pass": "Password:",
            "prompt_pass_wrong": "Wrong password, please re-enter:",
            "prompt_new_pass": "Welcome new player $id! Set your password:",
            "prompt_new_pass_empty": "Password cannot be empty, set again:",
            "login_success": "Login successful! Welcome, $name.",
            "void": "You are floating in the void.",
            "not_found": "You don't see any '$arg' here.",
            "exits": "Exits",
            "inventory": "Items",
            "livings": "Here are",
            "none": "None",
            "inv_empty": "Your inventory is empty.",
            "inv_header": "You are carrying the following items:",
            "get_what": "Get what?",
            "no_container": "There is no container called '$id' here.",
            "is_closed": "is closed.",
            "here": "here",
            "no_item_here": "You don't see any '$id' in $loc.",
            "get_living_err": "You cannot pick up living things.",
            "too_heavy_err": "is too heavy or fixed in place.",
            "loot_protected_err": "The loot of this corpse is protected, you cannot take it yet.",
            "inv_full_err": "Your inventory is full.",
            "corpse_run_success": "✨ You retrieved your remains, feeling your soul enriched and restoring some lost exp and potential.",
            "get_money": "You opened the money bag and obtained $m copper coins.",
            "ground": "the ground",
            "get_success": "You picked up $item from $from.",
            "say_get": "$name picked up $item.",
            "get_fail": "You failed to take that item.",
            "drop_what": "Drop what?",
            "no_item_inv": "You don't have any '$id' in your inventory.",
            "no_drop_err": "seems stuck to your hands, you cannot drop it!",
            "drop_success": "You dropped $item.",
            "say_drop": "$name dropped $item.",
            "drop_fail": "You cannot drop that item right now.",
            "go_where": "Go where? (e.g. go north)",
            "no_exit_err": "There is no exit in that direction.",
            "dest_missing_err": "The destination does not exist.",
            "say_leave": "$name left towards $dir.",
            "say_arrive": "$name arrived from $dir.",
            "move_fail_err": "You cannot go $dir.",
            "wear_what": "Wear what?",
            "not_armour_err": "is not armour.",
            "lv_req_err": "Your level is too low to equip $item (requires level $lv).",
            "wear_fail": "Failed to wear",
            "wear_success": "You put on $item. (Defence +$def)",
            "wield_what": "Wield what?",
            "not_weapon_err": "is not a weapon.",
            "wield_fail": "Failed to wield",
            "wield_success": "You wielded $item. (Attack +$atk)",
            "remove_what": "Remove what?",
            "remove_success": "You removed $item.",
            "no_equip_inv": "You are not equipped with anything called '$id'.",
            "appraise_what": "Appraise what?",
            "appraising": "You carefully examine $item...",
            "unidentified_err": "This item is not identified yet, you cannot see its detailed stats.",
            "item_info": "Item Info",
            "type": "Type",
            "weight": "Weight",
            "value": "Value",
            "coin_gold": "gold coins",
            "durability": "Durability",
            "lv_req": "Level Req",
            "atk_bonus": "Attack Bonus",
            "attribute": "Attribute",
            "def_bonus": "Defence Bonus",
            "slot": "Slot",
            "current_lang": "Current Language",
            "available_langs": "Available Languages",
            "lang_usage": "Usage",
            "unsupported_lang": "Unsupported language",
            "guild_already_joined": "You already belong to an organization. You must leave it before joining a new one.",
            "level_low_err": "Your level is too low to join $guild.",
            "stat_low_err": "Your $stat is too low to join $guild.",
            "guild_join_success": "🎉 Congratulations! You have joined $guild!",
            "guild_rank_is": "Your current rank is: $rank",
            "guild_max_rank": "You have already reached the highest rank in the guild.",
            "guild_exp_low": "Your guild contribution is insufficient (need $req), cannot be promoted.",
            "guild_promote_success": "✨ Your rank has been promoted! You are now $rank.",
            "quest_accept": "You accepted the quest: $quest",
            "quest_desc": "Description: $desc",
            "quest_complete": "✨ Quest completed: $quest!",
            "quest_already_accepted": "You have already accepted this quest.",
            "quest_item_missing": "You don't have enough $item ($got/$req).",
            "quest_item_give": "You handed over $count $item.",
            "npc_says": "$name tells you: \"$msg\"",
            "say_msg": "$name says: \"$msg\"",
            "emote_msg": "$name $msg",
            "npc_good_place": "This is a good place.",
            "npc_name_is": "My name is $name, nice to meet you.",
            "npc_no_topics": "I have nothing to say.",
            "npc_topics_list": "You can ask me about: $list",
            "minimap_title": "=== Minimap: $room ($x,$y,$z) ===",
            "minimap_legend": "Legend:  *  You  #  Visited  S  Safe  F  Forge  L  Lab  B  Bank  T  Tavern  A  Shop   ?   Unknown",
            "cmd_list": "Command List",
            "map_not_found": "You cannot draw a map from your current location.",
            "guild_exp_gain": "Your guild contribution increased by ",
            "stat_int": "Intelligence",
            "stat_str": "Strength",
            "cat_basic": "Basic",
            "cat_social": "Social",
            "cat_combat": "Combat",
            "cat_special": "Special",
            "cat_admin": "Admin",
            "cat_other": "Other",
            "quest_progress": "{g}[Quest Progress]{n} $quest: $current / $total",
            "quest_goal_met": "You have met the quest objectives, go back and report!",
            "quest_reward_get": "You obtained $item!",
            "quest_reward_item": "You received the reward: $item!",
            "label_hp": "HP",
            "label_mp": "MP",
            "label_commands": "📜 Commands",
            "label_actions": "🎭 Actions",
            "label_wealth": "Wealth",
            "label_atk": "Attack",
            "coin_copper": "copper coins",
            "coin_silver": "silver coins",
            "coin_cool_gold": "cool gold coins",
            "current_game_time": "Current Game Time",
            "total_game_minutes": "Total Game Minutes",
            "weather_clear": "The sky gradually clears, and sunlight bathes every corner of the earth.",
            "weather_cloudy": "A few dark clouds float by, and the sky becomes gloomy.",
            "weather_rainy": "Mist-like rain starts to fall from the sky, washing the dust of the world.",
            "weather_foggy": "A thick fog gradually rises around, making distant views blurry.",
            "weather_snowy": "Crystal snowflakes fall gracefully from the sky.",
            "desc_clear_day": "Sunny",
            "desc_clear_night": "Starlit",
            "desc_cloudy": "Cloudy",
            "desc_rainy": "Rainy",
            "desc_foggy": "Foggy",
            "desc_snowy": "Snowy",
            "weather_time_format": "[ %s / %s ]"
        ]),
        "zh-TW": ([
            "welcome": "歡迎回來，$name。",
            "what": "什麼？",
            "cmd_not_found": "找不到該指令。",
            "prompt_id": "請輸入您的帳號名稱：",
            "prompt_id_empty": "帳號不能為空，請重新輸入：",
            "prompt_pass": "請輸入密碼：",
            "prompt_pass_wrong": "密碼錯誤，請重新輸入密碼：",
            "prompt_new_pass": "歡迎新玩家 $id！為您的帳號設定密碼：",
            "prompt_new_pass_empty": "密碼不能為空，請重新設定密碼：",
            "login_success": "登入成功！歡迎來到這個世界，$name。",
            "void": "你飄浮在虛空中。",
            "not_found": "你看不到叫「$arg」的東西。",
            "exits": "出口",
            "inventory": "物品",
            "livings": "這裡有",
            "none": "無",
            "inv_empty": "你身上沒有任何東西。",
            "inv_header": "你身上帶著以下物品：",
            "get_what": "撿起什麼？",
            "no_container": "這裡沒有叫「$id」的容器。",
            "is_closed": "是關著的。",
            "here": "這裡",
            "no_item_here": "$loc 沒有叫「$id」的東西。",
            "get_living_err": "你不能撿起活物。",
            "too_heavy_err": "太重了，或者是被固定住了，你拿不起來。",
            "loot_protected_err": "這具屍體的戰利品暫時受保護，你目前無法拿取。",
            "inv_full_err": "你的背包裝不下了。",
            "corpse_run_success": "✨ 你取回了自己的遺物，靈魂感到一陣充實，恢復了部分損失的經驗與潛能。",
            "get_money": "你打開了錢袋，獲得了 $m 銅幣。",
            "ground": "地上",
            "get_success": "你從 $from 撿起了 $item。",
            "say_get": "$name 撿起了 $item。",
            "get_fail": "你無法拿走這個物品。",
            "drop_what": "丟下什麼？",
            "no_item_inv": "你身上沒有叫「$id」的東西。",
            "no_drop_err": "似乎黏在你的手上了，丟不掉！",
            "drop_success": "你放下了 $item。",
            "say_drop": "$name 放下了 $item。",
            "drop_fail": "你現在沒辦法丟下這個東西。",
            "go_where": "要往哪裡去？例如：go north",
            "no_exit_err": "那個方向沒有出路。",
            "dest_missing_err": "目的地不存在。",
            "say_leave": "$name 往 $dir 方向離開了。",
            "say_arrive": "$name 從 $dir 方向來到了這裡。",
            "move_fail_err": "你往 $dir 走不過去。",
            "wear_what": "穿上什麼？",
            "not_armour_err": "不是防具。",
            "lv_req_err": "你的等級不足，無法裝備 $item (需要等級 $lv)。",
            "wear_fail": "無法裝備",
            "wear_success": "你穿上了 $item。（防禦力 +$def）",
            "wield_what": "裝備什麼武器？",
            "not_weapon_err": "不是武器。",
            "wield_fail": "無法裝備",
            "wield_success": "你裝備了 $item。（攻擊力 +$atk）",
            "remove_what": "脫下什麼？",
            "remove_success": "你脫下了 $item。",
            "no_equip_inv": "你沒有裝備叫「$id」的東西。",
            "appraise_what": "鑑定什麼？",
            "appraising": "你仔細觀察 $item...",
            "unidentified_err": "這件物品尚未被鑑定，你看不出它的具體深淺。",
            "item_info": "物品資訊",
            "type": "種類",
            "weight": "重量",
            "value": "價值",
            "coin_gold": "金幣",
            "durability": "耐久",
            "lv_req": "需求等級",
            "atk_bonus": "攻擊力",
            "attribute": "屬性",
            "def_bonus": "防禦力",
            "slot": "部位",
            "current_lang": "當前語系",
            "available_langs": "可用語系",
            "lang_usage": "用法",
            "unsupported_lang": "不支援的語系",
            "guild_already_joined": "你已經有所屬的組織了，必須先退出才能加入新公會。",
            "level_low_err": "你的等級不足，無法加入 $guild。",
            "stat_low_err": "你的 $stat 不足，無法加入 $guild。",
            "guild_join_success": "🎉 恭喜！你正式加入了 $guild！",
            "guild_rank_is": "你現在的身分是：$rank",
            "guild_max_rank": "你已經達到了公會的最高職位。",
            "guild_exp_low": "你的公會貢獻度不足 (需要 $req)，無法晉升。",
            "guild_promote_success": "✨ 你的職位提升了！你現在是 $rank。",
            "quest_accept": "你承接了任務：$quest",
            "quest_desc": "任務描述：$desc",
            "quest_complete": "✨ 任務完成：$quest！",
            "quest_already_accepted": "你已經承接過這個任務了。",
            "quest_item_missing": "你身上的 $item 數量不足 ($got/$req)。",
            "quest_item_give": "你交出了 $count 個 $item。",
            "npc_says": "$name 告訴你：「$msg」",
            "say_msg": "$name 說：「$msg」",
            "emote_msg": "$name $msg",
            "npc_good_place": "這裡是個好地方。",
            "npc_name_is": "我叫 $name，請多指教。",
            "npc_no_topics": "我沒什麼好說的。",
            "npc_topics_list": "你可以問我關於：$list",
            "minimap_title": "=== 區域地圖：$room ($x,$y,$z) ===",
            "minimap_legend": "圖例:  *  你  #  已探索  S  安全  F  鐵匠  L  藥劑  B  銀行  T  酒館  A  商店   ?   未探索",
            "cmd_list": "指令列表",
            "map_not_found": "你目前所在的位置無法繪製地圖。",
            "guild_exp_gain": "你的公會貢獻度提升了 ",
            "stat_int": "智力",
            "stat_str": "力量",
            "cat_basic": "基本",
            "cat_social": "社交",
            "cat_combat": "戰鬥",
            "cat_special": "特殊",
            "cat_admin": "管理員",
            "cat_other": "其他",
            "quest_progress": "{g}【任務進度】{n} $quest：$current / $total",
            "quest_goal_met": "你已經達成了任務目標，快回去回報吧！",
            "quest_reward_get": "你獲得了 $item！",
            "quest_reward_item": "你獲得了獎勵物品：$item！",
            "label_hp": "生命",
            "label_mp": "法力",
            "label_commands": "📜 指令清單",
            "label_actions": "🎭 社交動作",
            "label_wealth": "財富",
            "label_atk": "攻擊",
            "coin_copper": "銅幣",
            "coin_silver": "銀幣",
            "coin_cool_gold": "酷金幣",
            "current_game_time": "目前時間",
            "total_game_minutes": "遊戲總分鐘",
            "weather_clear": "天空逐漸放晴，陽光灑滿了大地的每一個角落。",
            "weather_cloudy": "幾朵烏雲飄過，天空變得陰沉了下來。",
            "weather_rainy": "天空下起了綿綿細雨，洗滌著塵世。",
            "weather_foggy": "四周漸漸騰起一陣濃霧，遠方的景物變得模糊不清。",
            "weather_snowy": "晶瑩的雪花從天空紛紛揚揚地落下。",
            "desc_clear_day": "晴朗",
            "desc_clear_night": "星光燦爛",
            "desc_cloudy": "多雲",
            "desc_rainy": "下雨",
            "desc_foggy": "濃霧",
            "desc_snowy": "下雪",
            "weather_time_format": "【 %s / %s 】"
        ]),
        "zh-CN": ([
            "welcome": "欢迎回來，$name。",
            "what": "什么？",
            "cmd_not_found": "找不到该指令。",
            "prompt_id": "请输入您的账号名称：",
            "prompt_id_empty": "账号不能为空，请重新输入：",
            "prompt_pass": "请输入密码：",
            "prompt_pass_wrong": "密码错误，请重新输入密码：",
            "prompt_new_pass": "欢迎新玩家 $id！为您的账号设定密码：",
            "prompt_new_pass_empty": "密码不能为空，请重新设定密码：",
            "login_success": "登录成功！欢迎來到这个世界，$name。",
            "void": "你飘浮在虚空中。",
            "not_found": "你看不到叫「$arg」的东西。",
            "exits": "出口",
            "inventory": "物品",
            "livings": "这里有",
            "none": "无",
            "inv_empty": "你身上没有任何东西。",
            "inv_header": "你身上带着以下物品：",
            "get_what": "捡起什么？",
            "no_container": "这里没有叫「$id」的容器。",
            "is_closed": "是关着的。",
            "here": "这里",
            "no_item_here": "$loc 没有叫「$id」的东西。",
            "get_living_err": "你不能捡起活物。",
            "too_heavy_err": "太重了，或者是被固定住了，你拿不起来。",
            "loot_protected_err": "這具屍體的戰利品暫時受保護，你目前無法拿取。",
            "inv_full_err": "你的背包裝不下了。",
            "corpse_run_success": "✨ 你取回了自己的遗物，灵魂感到一阵充实，恢复了部分損失的经验与潜能。",
            "get_money": "你打开了钱袋，获得了 $m 铜币。",
            "ground": "地上",
            "get_success": "你从 $from 捡起了 $item。",
            "say_get": "$name 捡起了 $item。",
            "get_fail": "你无法拿走这个物品。",
            "drop_what": "丢下什么？",
            "no_item_inv": "你身上没有叫「$id」的東西。",
            "no_drop_err": "似乎黏在你的手上了，丢不掉！",
            "drop_success": "你放下了 $item。",
            "say_drop": "$name 放下了 $item。",
            "drop_fail": "你现在没办法丟下这个东西。",
            "go_where": "要往哪里去？例如：go north",
            "no_exit_err": "那个方向没有出路。",
            "dest_missing_err": "目的地不存在。",
            "say_leave": "$name 往 $dir 方向離開了。",
            "say_arrive": "$name 從 $dir 方向來到了這裡。",
            "move_fail_err": "你往 $dir 走不過去。",
            "wear_what": "穿上什么？",
            "not_armour_err": "不是防具。",
            "lv_req_err": "你的等级不足，无法装备 $item (需要等级 $lv)。",
            "wear_fail": "无法装备",
            "wear_success": "你穿上了 $item。（防御力 +$def）",
            "wield_what": "装备什么武器？",
            "not_weapon_err": "不是武器。",
            "wield_fail": "无法装备",
            "wield_success": "你装备了 $item。（攻击力 +$atk）",
            "remove_what": "脱下什么？",
            "remove_success": "你脱下了 $item。",
            "no_equip_inv": "你没有装备叫「$id」的東西。",
            "appraise_what": "鑑定什么？",
            "appraising": "你仔细观察 $item...",
            "unidentified_err": "這件物品尚未被鑑定，你看不出它的具體深淺。",
            "item_info": "物品信息",
            "type": "种类",
            "weight": "重量",
            "value": "价值",
            "coin_gold": "金币",
            "durability": "耐久",
            "lv_req": "需求等级",
            "atk_bonus": "攻击力",
            "attribute": "属性",
            "def_bonus": "防御力",
            "slot": "部位",
            "current_lang": "当前语系",
            "available_langs": "可用语系",
            "lang_usage": "用法",
            "unsupported_lang": "不支持的语系",
            "guild_already_joined": "你已经有所属的组织了，必须先退出才能加入新公會。",
            "level_low_err": "你的等级不足，无法加入 $guild。",
            "stat_low_err": "你的 $stat 不足，無法加入 $guild。",
            "guild_join_success": "🎉 恭喜！你正式加入了 $guild！",
            "guild_rank_is": "你现在的身份是：$rank",
            "guild_max_rank": "你已经达到了公会的最高职位。",
            "guild_exp_low": "你的公会贡献度不足 (需要 $req)，无法晋升。",
            "guild_promote_success": "✨ 你的职位提升了！你現在是 $rank。",
            "quest_accept": "你承接了任務：$quest",
            "quest_desc": "任務描述：$desc",
            "quest_complete": "✨ 任務完成：$quest！",
            "quest_already_accepted": "你已经承接过這個任務了。",
            "quest_item_missing": "你身上 的 $item 數量不足 ($got/$req)。",
            "quest_item_give": "你交出了 $count 個 $item。",
            "npc_says": "$name 告诉你：“$msg”",
            "say_msg": "$name 说：“$msg”",
            "emote_msg": "$name $msg",
            "npc_good_place": "这里是个好地方。",
            "npc_name_is": "我叫 $name，请多指教。",
            "npc_no_topics": "我没什么好说的。",
            "npc_topics_list": "你可以问我关于：$list",
            "minimap_title": "=== 区域地图：$room ($x,$y,$z) ===",
            "minimap_legend": "图例:  *  你  #  已探索  S  安全  F  铁匠  L  药剂  B  银行  T  酒馆  A  商店   ?   未探索",
            "cmd_list": "指令列表",
            "map_not_found": "你目前所在的位置无法绘制地图。",
            "guild_exp_gain": "你的公会贡献度提升了 ",
            "stat_int": "智力",
            "stat_str": "力量",
            "cat_basic": "基本",
            "cat_social": "社交",
            "cat_combat": "战斗",
            "cat_special": "特殊",
            "cat_admin": "管理员",
            "cat_other": "其他",
            "quest_progress": "{g}【任务进度】{n} $quest：$current / $total",
            "quest_goal_met": "你已经达成了任务目标，快回去回报吧！",
            "quest_reward_get": "你获得了 $item！",
            "quest_reward_item": "你获得了奖励物品：$item！",
            "label_hp": "生命",
            "label_mp": "法力",
            "label_commands": "📜 指令清单",
            "label_actions": "🎭 社交动作",
            "label_wealth": "财富",
            "label_atk": "攻击",
            "coin_copper": "铜币",
            "coin_silver": "银币",
            "coin_cool_gold": "酷金币",
            "current_game_time": "目前时间",
            "total_game_minutes": "游戏总分钟",
            "weather_clear": "天空逐渐放晴，阳光洒满了大地的每一个角落。",
            "weather_cloudy": "几朵乌云飘过，天空变得阴沉了下來。",
            "weather_rainy": "天空下起了绵绵细雨，洗涤着尘世。",
            "weather_foggy": "四周渐渐騰起一阵浓雾，远方的景物变得模糊不清。",
            "weather_snowy": "晶莹的雪花从天空纷纷扬扬地落下。",
            "desc_clear_day": "晴朗",
            "desc_clear_night": "星光灿烂",
            "desc_cloudy": "多云",
            "desc_rainy": "下雨",
            "desc_foggy": "浓雾",
            "desc_snowy": "下雪",
            "weather_time_format": "【 %s / %s 】"
        ])
    ]);
}

string translate(string key, string lang) {
    if (!lang || !translations[lang]) {
        if (strsrch(lang, "zh-") == 0) lang = "zh-TW";
        else lang = "en";
    }

    if (translations[lang] && translations[lang][key]) {
        return translations[lang][key];
    }
    
    return key;
}

mapping query_all_translations() { return translations; }

// 廣播事件訊息給房間內的所有玩家 (自動按玩家語系翻譯)
void broadcast_event(object room, string key, mapping params) {
    if (!room) return;
    
    object *inv = all_inventory(room);
    if (!inv || sizeof(inv) == 0) return;

    // 方向本地化字典
    mapping dir_map = ([
        "north": ([ "en": "the north", "zh-TW": "北方", "zh-CN": "北方" ]),
        "south": ([ "en": "the south", "zh-TW": "南方", "zh-CN": "南方" ]),
        "east":  ([ "en": "the east",  "zh-TW": "東方", "zh-CN": "东方" ]),
        "west":  ([ "en": "the west",  "zh-TW": "西方", "zh-CN": "西方" ]),
        "up":    ([ "en": "above",     "zh-TW": "上方", "zh-CN": "上方" ]),
        "down":  ([ "en": "below",     "zh-TW": "下方", "zh-CN": "下方" ]),
        "here":  ([ "en": "somewhere", "zh-TW": "附近", "zh-CN": "附近" ])
    ]);
    
    foreach (object ob in inv) {
        if (!userp(ob) || !is_interactive(ob)) continue;
        
        string lang = ob->query_lang();
        if (!lang) lang = "en";
        
        string msg = translate(key, lang);
        if (msg == key) continue;
        
        // 替換參數
        if (mapp(params)) {
            string *ks = keys(params);
            foreach (string p_key in ks) {
                mixed p_val = params[p_key];
                
                // 🚀 關鍵修正：支援物件本地化名稱
                if (objectp(p_val)) {
                    p_val = p_val->query_localized_name(lang);
                } else if (p_key == "$dir" && stringp(p_val) && dir_map[p_val]) {
                    // 🚀 特殊處理 $dir：如果值在方向字典中，則進行翻譯
                    p_val = dir_map[p_val][lang] ? dir_map[p_val][lang] : dir_map[p_val]["en"];
                }
                
                msg = replace_string(msg, p_key, to_string(p_val));
            }
        }
        
        tell_object(ob, msg + "\n");
    }
}
