inherit ROOM;
void create() {
	set( "short", "新區域J-N" );
	set( "object", ([
		"amount5"  : 1,
		"file1"    : "/open/ping/questsfan/obj/diamond_armor",
		"file2"    : "/open/ping/questsfan/obj/diamond_belt",
		"file5"    : "/open/ping/questsfan/obj/diamond_cloak",
		"file6"    : "/open/ping/questsfan/obj/diamond_hairpin",
		"amount9"  : 1,
		"file7"    : "/open/ping/questsfan/obj/diamond_boots",
		"file4"    : "/open/ping/questsfan/obj/diamond_legging",
		"amount2"  : 1,
		"file8"    : "/open/ping/questsfan/obj/diamond_skirt",
		"amount1"  : 1,
		"amount7"  : 1,
		"amount3"  : 1,
		"amount4"  : 1,
		"file9"    : "/open/sky/obj/lucky_grasslink",
		"amount6"  : 1,
		"file3"    : "/open/ping/questsfan/obj/diamond_hands",
		"amount8"  : 1,
	]) );
	set( "build", 10248 );
	set( "owner", "soldier" );
	set( "exits", ([
		"south"     : "/open/clan/ou-cloud-club/room/room574",
	]) );
	set( "long", @LONG
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
...................
LONG);
	setup();
	replace_program(ROOM);
}
