// 「長拳」為尋常的拳腳功夫, 一般拳師、保鏢都可以掛上去。
// 由於是 NPC 專用的 SKILL, 故省略 valid_learn 與 practice_skill 的設定
// make by Onion
#include <combat.h>
inherit SKILL;

mapping *action = ({
([ "action":"$N雙手如勾﹐一招「金龍探爪」﹐身形如一條金龍往$n$l攻了過去",
	"dodge": -3,
	"parry": -2,
	"damage": 25,
	"force":  40,
	"damage_type":	"割傷",
]),

([ "action":"$N氣沉丹田﹐「龍行一式」蓄勢待發﹐一拳打向$n的$l",
	"dodge": -4,
	"parry": -5,
        "damage": 22,
        "force": 30,
	"damage_type": "瘀傷",
]),

([ "action":"$N身形一轉﹐使出「秋風落葉」﹐向$n$l橫掃而去",
	"dodge": -5,
	"parry": -2,
        "damage": 20,
       	"force": 40,
	"damage_type": "瘀傷",
]),
([ "action":"$N擊出「龍門三擊浪」﹐拳勁直直的撞向$n$l",
	"dodge": 5,
	"parry": 0,
        "damage": 70,
       	"force": 50,
	"damage_type": "瘀傷",
]),
([ "action":"$N突然一招「翻身打盤」﹐身形刁鑽的朝$n$l一拳直去",
	"dodge": 0,
	"parry": -2,
        "damage": 10,
       	"force": 30,
	"damage_type": "瘀傷",
]),
([ "action":"$N雙手一展﹐使出「金鵰展翅」﹐由上而下拳打$n$l",
	"dodge": -5,
	"parry": -2,
        "damage": 20,
       	"force": 30,
	"damage_type": "瘀傷",
	
]),
([ "action":"$N大喝一聲﹐「蒼龍歸海」﹐雙手緩緩的推向$n$l",
	"dodge": -5,
	"parry": -2,
        "damage": 29,
       	"force": 30,
	"damage_type": "瘀傷",
]),
([ "action":"$N勢如猛虎出閘﹐「黑虎偷心」直襲$n$l",
        "dodge": -3,
        "parry": -2,
        "damage": 20,
        "force":  40,
        "damage_type":  "瘀傷",
]),

([ "action":"$N使出「進步連環」﹐一連三拳打向$n$l",
        "dodge": -4,
        "parry": -1,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀傷",
]),

([ "action":"$N斥喝一聲﹐使出「獨劈華山」﹐一掌向$n斬了下去",
        "dodge": -5,
        "parry": 0,
        "damage": 70,
        "force": 4,
        "damage_type": "瘀傷",
]),
([ "action":"$N身形一退﹐一招「倒打金鐘」反而打向$n$l",
        "dodge": 5,
        "parry": 0,
        "damage": 80,
        "force": 5,
        "damage_type": "瘀傷",
]),
([ "action":"$N一轉身﹐「黃龍捲尾」一拳向$n$l飛去",
        "dodge": -3,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀傷",
]),
([ "action":"$N一招「如封似閉」﹐雙手忽上忽下﹐游移不定的擊向$n$l",
        "dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type": "瘀傷",
]),
([ "action":"$N右手往前一推﹐一招「推窗望月」向$n推去",
	"dodge": -5,
	"parry": -2,
	"damage": 20,
	"force": 3,
	"damage_type":"瘀傷",
]),
([ "action":"$N左手陰拳﹐打出一招「白猿摘果」﹐直襲$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀傷",
]),
([ "action":"$N身形一扭﹐使出「玉帶圍腰」﹐拳背直擊$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀傷",
]),
([ "action":"$N雙手握拳﹐「抽撤連環」向$n$l擊去",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"瘀傷",
          ]),
([ "action":"$N雙手合掌﹐「寒雞拜佛」刺向$n$l",
	"dodge": -5,
        "parry": -2,
        "damage": 20,
        "force": 3,
        "damage_type":"刺傷",
]),
});

mapping query_action(object me, object weapon)
{
	  return action[random(sizeof(action))];
}

int valid_enable(string usage) 
{
	  return (usage=="unarmed");
}
